### ISSUE TITLE
GP Style Guide

### ISSUE THREAD

**Issue by vlbee** [fac-13/GP_ProjectBernadette#1]
Waiting for GP brand style guide

**Comment by OliviaMervynSmith** [comment]
[P606 GP Brand Guidelines-9.pdf](https://github.com/fac-13/GP_ProjectBernadette/files/2053343/P606.GP.Brand.Guidelines-9.pdf)

**Comment by vlbee** [comment]
Thanks Olivia!

**Comment by vlbee** [comment]
Your style guide is super helpful!  
Do you have your logo and the icons available as vector files (.ai, .svg. .eps format) you could share with us? Or as standalone jpg images? No worries if not!

**Comment by OliviaMervynSmith** [comment]
![gp_logo-cmyk](https://user-images.githubusercontent.com/39738457/40714466-9c1be290-63fa-11e8-8049-1094347e9511.jpg)

![gp_icons](https://user-images.githubusercontent.com/39738457/40714556-e0072d34-63fa-11e8-9e8f-0af776eac9a8.png)
