### ISSUE TITLE
User Journey Script

### ISSUE THREAD

**Issue by vlbee** [fac-13/GP_ProjectBernadette#2]
Acceptance Criteria: 
- [x] Copy (wording) for the entire user journey typed up here
- [x] Questions and Answer option for all questions based on Cathy's notes
- [x] reviewed and proofread by 3 people
- [x] approved by client

**Comment by tspeed90** [comment]
@OliviaMervynSmith Updated flow chart after receiving feedback on the wording. :smile:

Note: Actual links were provided which will be used in the final product, but were omitted on the flow chart for simplicity.

![screenshot from 2018-06-01 10-48-30](https://user-images.githubusercontent.com/31294722/40834879-ed44421c-6589-11e8-864b-11b984c1ae5b.png)

![screenshot from 2018-06-01 10-48-19](https://user-images.githubusercontent.com/31294722/40834878-ed24cdba-6589-11e8-9aa0-043216549e27.png)
