### ISSUE TITLE
Research - Do we need a server?

### ISSUE THREAD

**Issue by vlbee** [fac-13/GP_ProjectBernadette#21]
Relates to #19 contact Rory

Based on the plan for the prototype, I don't think we need a server and can build a straight up React App. 

- Question and Answer Tree can be built as a json object, delivered to FE and we can write our own cool logic function to walk the tree. 
- Bernie's answers can be stored in State
- Upon submission of info for a callback, we can send the info from State direct to GP via email as they requested. 

**Benefits:**
Focus on what matters to the client: a simply prototype they can use off the bat to test on their existing website for real user uptake before investing in more complex data architecture.

Should GP want to expand and grow the product, the focus of the next sprint can be to integrate the slick existing front-end app we build with a more robust and scalable BE system to expand the questionnaire format.

To be discussed!

**Comment by tspeed90** [comment]
Something to consider is when the user sends their data through the form to be contacted later. There may be security issues around that that we may need to think about in making this decision.

**Comment by tspeed90** [comment]
We've decided that we will need a server for the project.
