### ISSUE TITLE
Bad link (general info)

### ISSUE THREAD

**Issue by tspeed90** [fac-13/GP_ProjectBernadette#65]
We need to reach out to Kathy to ask about the link for the general advice page she wants us to route to. The one she provided me with doesn't seem like the one she probably meant to give us. 

Link provided: https://www.grandparentsplus.org.uk/pages/faqs/category/advice-and-information#

**Comment by tspeed90** [comment]
I reached out to @OliviaMervynSmith and Kathy regarding this on Friday afternoon. Just awaiting their reply and this will be updated.

**Comment by vlbee** [comment]
closed in PR #108
